export interface ApiSuccessResponse<T> {
  data: T;
  meta?: PaginationMeta | Record<string, unknown>;
}

export interface ApiErrorResponse {
  statusCode: number;
  errorCode: string;
  message: string;
  timestamp: string;
  path: string;
  details?: Record<string, unknown>;
}

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface PaginationQuery {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}

export type ErrorCodePrefix =
  | 'WMS_AUTH'
  | 'WMS_LIC'
  | 'WMS_INV'
  | 'WMS_ORD'
  | 'WMS_RCP'
  | 'WMS_WH'
  | 'WMS_CLIENT'
  | 'WMS_ITEM'
  | 'WMS_VAL'
  | 'WMS_SYS';

export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'WMS_AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'WMS_AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'WMS_AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'WMS_AUTH_FORBIDDEN',
  AUTH_UNAUTHORIZED: 'WMS_AUTH_UNAUTHORIZED',
  LIC_INVALID: 'WMS_LIC_INVALID',
  LIC_EXPIRED: 'WMS_LIC_EXPIRED',
  LIC_FEATURE_NOT_LICENSED: 'WMS_LIC_FEATURE_NOT_LICENSED',
  LIC_LIMIT_REACHED: 'WMS_LIC_LIMIT_REACHED',
  INV_INSUFFICIENT_STOCK: 'WMS_INV_INSUFFICIENT_STOCK',
  INV_LOT_NOT_FOUND: 'WMS_INV_LOT_NOT_FOUND',
  INV_LOT_HELD: 'WMS_INV_LOT_HELD',
  INV_INCOMPATIBLE_LOCATION: 'WMS_INV_INCOMPATIBLE_LOCATION',
  INV_HOLD_NOT_FOUND: 'WMS_INV_HOLD_NOT_FOUND',
  INV_HOLD_ALREADY_RELEASED: 'WMS_INV_HOLD_ALREADY_RELEASED',
  INV_ADJUSTMENT_NOT_FOUND: 'WMS_INV_ADJUSTMENT_NOT_FOUND',
  INV_ADJUSTMENT_INVALID_STATUS: 'WMS_INV_ADJUSTMENT_INVALID_STATUS',
  INV_INVALID_LOT_STATUS: 'WMS_INV_INVALID_LOT_STATUS',
  INV_LOCATION_NOT_FOUND: 'WMS_INV_LOCATION_NOT_FOUND',
  INV_LOCATION_INACTIVE: 'WMS_INV_LOCATION_INACTIVE',
  INV_TEMP_CLASS_MISMATCH: 'WMS_INV_TEMP_CLASS_MISMATCH',
  INV_HAZMAT_NOT_ALLOWED: 'WMS_INV_HAZMAT_NOT_ALLOWED',
  INV_LOCATION_RESERVED: 'WMS_INV_LOCATION_RESERVED',
  ORD_NOT_FOUND: 'WMS_ORD_NOT_FOUND',
  ORD_INVALID_STATUS: 'WMS_ORD_INVALID_STATUS',
  ORD_ALREADY_EXISTS: 'WMS_ORD_ALREADY_EXISTS',
  ORD_CARTON_OPEN: 'WMS_ORD_CARTON_OPEN',
  RCP_NOT_FOUND: 'WMS_RCP_NOT_FOUND',
  RCP_INVALID_STATUS: 'WMS_RCP_INVALID_STATUS',
  INB_RECEIPT_NOT_FOUND: 'WMS_INB_RECEIPT_NOT_FOUND',
  INB_LINE_NOT_FOUND: 'WMS_INB_LINE_NOT_FOUND',
  INB_INVALID_STATUS: 'WMS_INB_INVALID_STATUS',
  INB_INCOMPLETE_LINES: 'WMS_INB_INCOMPLETE_LINES',
  INB_APPOINTMENT_NOT_FOUND: 'WMS_INB_APPOINTMENT_NOT_FOUND',
  WH_NOT_FOUND: 'WMS_WH_NOT_FOUND',
  CLIENT_NOT_FOUND: 'WMS_CLIENT_NOT_FOUND',
  ITEM_NOT_FOUND: 'WMS_ITEM_NOT_FOUND',
  BILLING_RATE_CARD_NOT_FOUND: 'WMS_BILLING_RATE_CARD_NOT_FOUND',
  BILLING_INVOICE_NOT_FOUND: 'WMS_BILLING_INVOICE_NOT_FOUND',
  BILLING_CHARGE_NOT_FOUND: 'WMS_BILLING_CHARGE_NOT_FOUND',
  BILLING_INVALID_STATE: 'WMS_BILLING_INVALID_STATE',

  VAL_VALIDATION_FAILED: 'WMS_VAL_VALIDATION_FAILED',
  SYS_INTERNAL: 'WMS_SYS_INTERNAL',
  SYS_NOT_FOUND: 'WMS_SYS_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
